In [ ]:
a = ["John", "Charles", "Mike"]
b = ["Jenny", "Christy", "Monica"]

x = dict(zip(a, b))
print(x)

y  = list(zip(a, b))
print(y)

z = set(zip(a, b))
print(z)

c = tuple(zip(a, b))
print(c)







In [38]:
fruit_list = ['apple','banana','mango','orange','kiwi','grape']
print(fruit_list)
#fruit_list.append('watermelon')

fruit_list[::-1]
fruit_list[-1:2:-1]
fruit_list.reverse()
#fruit_list.sort()


['apple', 'banana', 'mango', 'orange', 'kiwi', 'grape']


['grape', 'kiwi', 'orange']

In [45]:
sorted(fruit_list,reverse=True)
fruit_list.reverse()
print(fruit_list)

fruit_list +  fruit_list


['apple', 'banana', 'mango', 'orange', 'kiwi', 'grape']


['apple',
 'banana',
 'mango',
 'orange',
 'kiwi',
 'grape',
 'apple',
 'banana',
 'mango',
 'orange',
 'kiwi',
 'grape']

In [48]:
import numpy as np
fruit_list = np.array(fruit_list)
print(type(fruit_list))
fruit_list.reshape()

<class 'numpy.ndarray'>


(6,)

In [46]:
import numpy as np
twod_array = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
twod_array.shape
#twod_array.flatten()
twod_array[0:2,0:2]

arr = twod_array[1:3,1:3]

arr.transpose()




array([[5, 8],
       [6, 9]])

In [49]:
age = 5

if age <= 5:
    print("You are a kid")
if age < 15:
    print("You are 5 years old")
if age < 18:
    print("You are 18 years old")
else:
    print("You are older than 5")


You are a kid
You are 5 years old
You are 18 years old


In [11]:
print(range(5))
s = ""
for i in range(1,3):
    s = s + str(i)
print(s)

range(0, 5)
12


In [3]:
n = 3
s = ""
i = 1
while i <= n:
    s = s + str(i)
    i = i + 1
print(s)



12345


# Callback function

In [1]:
def greet(name,callback):
   callback(name)

def greet_in_english(name):
    print("Hello " + name)

def greetInspanish(name):
    print("Hola " + name)

def greetInArabic(name):
    print("Salam " + name)

def greetInFrench(name):
    print("Bonjour " + name)
def greetInHindi(name):
    print("Namaste " + name)

greet("John", greet_in_english)
greet("John",greetInspanish)
greet("John",greetInArabic)
greet("John",greetInFrench)
greet("John",greetInHindi)


Hello John
Hola John
Salam John
Bonjour John
Namaste John


In [33]:
def swap_case(s):
  swapped = ""
  for x in s:
   if x.isupper():
        swapped += x.lower()
        s = s.replace(x, x.lower())
   else:
        swapped += x.upper()
        s = s.replace(x, x.upper())

  return s



print(swap_case("HackerRank.com presents Pythonist 2."))



HACKERRANK.COM pRESENTS pYTHONIST 2.


In [ ]:
n = 2
val = n

if n % 2 == 1:
    print("Weird")
elif

In [3]:
mark_lst = [70,85,90,95,100]
sum(mark_lst[1:3])

175

In [7]:
groceries = {
    "James": [10, 2, 5, 7, 9, 4, 6],
    "Tom": [1, 12, 3, 0, 1, 2, 5],
    "Sam": [9, 5, 4, 3, 2, 1, 3],
}

def most_purchases(groceries):
  x = {}
  for name,lst in groceries.items():
    tot = sum(lst)
    x[name] = tot

  print(max(x.items()))
  return max(x.items() , key=lambda item: item[1])

most_purchases(groceries)

('Tom', 24)


('James', 43)

In [6]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

counter = 0
avg_lst = []
sum = 0;
for wait in dailywts:
    print(f"{wait:0.2f}")
    counter += 1
    sum  = sum + wait
    if counter == 7:
        avg_lst.append(sum/counter)
        sum = 0
        counter = 0
#print(type(dailywts))
print(avg_lst)
print(len(avg_lst))

185.00
184.80
184.60
184.40
184.20
184.00
183.80
183.60
183.40
183.20
183.00
182.80
182.60
182.40
182.20
182.00
181.80
181.60
181.40
181.20
181.00
180.80
180.60
180.40
180.20
180.00
179.80
179.60
179.40
179.20
179.00
178.80
178.60
178.40
178.20
[np.float64(184.4), np.float64(183.0), np.float64(181.6), np.float64(180.2), np.float64(178.8)]
5


In [21]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

#print(dailywts)

reshp = dailywts.reshape(5,7)
reshp_means = reshp.mean(axis=1)
print(reshp_means)


# [185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
#  182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
#  180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]

[182.2 182.  181.8 181.6 181.4 181.2 181. ]


In [20]:
import numpy as np

np_arr = np.arange(1,6,2)

#np_arr = np_arr[:, :-1]
np.reshape(4,-1)

print(np_arr)
print(len(np_arr))


nu_arr = np.array([
    [1, 3, 5, 7, 9, 11, 13],
    [17, 19, 21, 23, 25, 27, 29],
    [33, 35, 37, 39, 41, 43, 45],
    [49, 51, 53, 55, 57, 59, 61]
])


#
print(nu_arr)
print("shape:", nu_arr.shape)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63]
32
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
shape: (4, 7)


In [9]:
import numpy as np

nola = 1 + 16 * np.arange(4)[:, None] + 2 * np.arange(7)
print(nola)
print("shape:", nola.shape)

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
shape: (4, 7)


In [9]:
import  numpy as np
nre_arr = np.arange(1,10)
nre_arr.shape = (3,3)
print(nre_arr)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy as np

# Read the dimensions (rows = X, columns = Y)
parts = input("Enter two integers (rows and columns) separated by space: ").split()
if len(parts) != 2:
    raise ValueError(f"Expected 2 values for rows and columns, got {len(parts)}")

X, Y = map(int, parts)

# Read the matrix rows
data = []
for i in range(X):
    row = list(map(int, input().split()))
    if len(row) != Y:
        raise ValueError(f"Expected {Y} columns in row {i+1}, got {len(row)}")
    data.append(row)

# Create the NumPy array
mat = np.array(data, dtype=int)

print("Matrix shape:", mat.shape)
print(mat)


Matrix shape: (2, 2)
[[2 1]
 [2 4]]
