# Numpy Practice

In [7]:
import numpy as np
li = [1,2,3,4,5]
tu = (1,2,3,4,5)
arr  = np.array(li)
print(type(arr))

nested_list = [[1,2,3],
               [4,5,6],
               [7,8,9]]
na_nested_list = np.array(nested_list)
print("3 x 3 "  , na_nested_list.shape)
print("Dimension of array" , na_nested_list.ndim)
print("number of elements", na_nested_list.size)
print("data type",na_nested_list.dtype)
print(arr.ndim)

mix_array = np.array([[1,2,3],[4,5,'hi']],dtype='U11')
print(mix_array.dtype)

mix_array2 = np.array([ [25,65] , ["a",8] , [32,26] ] )
print(mix_array.dtype)

<class 'numpy.ndarray'>
3 x 3  (3, 3)
Dimension of array 2
number of elements 9
data type int64
1
<U11
<U11


# Built-in functions


In [37]:
np.arange(1,10,2)
np.arange(0.5,30.5)
# Random numbers
rand_arr = np.random.randint(1,10, size=(3,2))
#print(rand_arr)

rand_arr2 = np.random.randint(1,10,10)
#print(rand_arr2)

print(rand_arr)

reshaped = rand_arr.reshape(2,3,1)  #### This need more detail explanation

print(reshaped)
#print(reshaped.ndim)



[[5 2]
 [9 6]
 [9 9]]
[[[5]
  [2]
  [9]]

 [[6]
  [9]
  [9]]]


In [38]:
rand_arr.transpose()

array([[5, 9, 9],
       [2, 6, 9]])

In [92]:
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

arr = np.array([[10,11,12],
                [13,14,15],
                [16,17,18]])


arr1 = [10,11,12]
arr2 = [2,1,2]
print(array_2d[1:2,0:3])

#arr = np.hstack(array_2d)
print(arr.ndim)
#np.vstack(array_2d)

np.trace(array_2d)

np.sum(array_2d)

np.power(array_2d,arr)


[[4 5 6]]
2


array([[                 1,               2048,             531441],
       [          67108864,         6103515625,       470184984576],
       [    33232930569601,   2251799813685248, 150094635296999121]])

In [99]:
print(np.zeros((3,4)))
ones_arr = np.ones((2,3),dtype='int32')
print(ones_arr)
empty_arr = np.empty((2,3),dtype='int32')
print(empty_arr)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


In [2]:
import  numpy as np

loop_2d_array = np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9]])

print(loop_2d_array.ndim)

for ar in loop_2d_array:
    for val in ar:
        print(val)


for x  in np.nditer(loop_2d_array):
    print(x)

2
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [1]:
pip list

Package                   Version
------------------------- --------------
anyio                     4.10.0
appnope                   0.1.4
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.5
bleach                    6.2.0
certifi                   2025.8.3
cffi                      2.0.0
charset-normalizer        3.4.3
comm                      0.2.3
contourpy                 1.3.0
cycler                    0.12.1
debugpy                   1.8.17
decorator                 5.2.1
defusedxml                0.7.1
exceptiongroup            1.3.0
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.60.0
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna          

In [2]:
import numpy as np
li = [1,2,3,4,5]
tu = (1,2,3,4,5)
arr  = np.array(li)
print(type(arr))

<class 'numpy.ndarray'>


In [17]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.ndim)
transposed_array = np.transpose(array_3d, axes=(2, 0, 1))
#print(transposed_array)

3


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6 ,7,8])
# Reshape 1D array of 6 elements to 2D array with 2 rows and 3 columns
reshaped_arr = np.reshape(arr, (4, 2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:

arr = np.arange(24)
print(arr)
reshaped_arr = arr.reshape(2,3,4)
print(reshaped_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [1]:
import numpy as np
array_3d = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 109]
    ]
]

array_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

new_arr = np.arange(15,40,3)
new_arr = new_arr.reshape(3,3)
print(new_arr)
td_array = np.array(array_3d)
tud_array = np.array(array_2d)
concat_arr = np.concatenate((tud_array, new_arr) , axis=0)
hstx = np.vstack((tud_array, new_arr))
print(td_array.shape)
print(td_array.ndim)
print(td_array.dtype)
print(td_array.size)
print(td_array.min())
print(td_array.max())
print(td_array.sum())
print(td_array.mean())
print(td_array.std())
print(td_array.var())
print(td_array.trace())

print(hstx)



[[15 18 21]
 [24 27 30]
 [33 36 39]]
(3, 3, 3)
3
int64
27
1
109
460
17.037037037037038
19.479298568026827
379.44307270233196
[ 39  42 127]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [15 18 21]
 [24 27 30]
 [33 36 39]]
